services:
  # 1. Nosso Banco de Dados
  mongodb:
    image: mongo
    container_name: credit-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Nosso Message Broker (Kafka com KRaft)
  kafka:
    image: apache/kafka:latest
    container_name: credit-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - "9092:9092"
      - "9094:9094"

  # 3. O Nosso Microsserviço
  credit-approval-service:
    build: .
    container_name: credit-approval-service
    ports:
      - "8080:8080"
    environment:
      # Aqui nós injetamos os nomes dos containers que configuramos no application.yml!
      - MONGODB_URI=mongodb://mongodb:27017/credit_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - kafka

volumes:
  mongo_data: